
stages:
  - terraform
  - authenticate
  - loadBalancer

terraform_apply:
  stage: terraform
  image: hashicorp/terraform:latest  # Use a Terraform image
  script:
    - terraform --version  # Check Terraform version
    # Initialize Terraform
    - terraform init
    # Plan the changes (Optional)
    - terraform plan -out=tfplan
    # Apply the changes (Automate infrastructure setup)
    - terraform apply -auto-approve tfplan

  artifacts:
    paths:
      - terraform.tfstate  # Save Terraform state as an artifact

authenticate:
  stage: authenticate
  image: google/cloud-sdk:latest
  dependencies: 
  - terraform_apply
  script:
    # Set up WIF-based authentication
    - gcloud auth login --brief --cred-file=${GOOGLE_APPLICATION_CREDENTIALS}
    - gcloud config set project $DEVSHELL_PROJECT_ID


compute engine :
  stage : loadBalancer
  image: google/cloud-sdk:latest
  dependencies: 
  - authenticate
  script :
    - gcloud auth activate-service-account --key-file=${SA_REVIEW_KEY}
    - gcloud config set project $DEVSHELL_PROJECT_ID
    - gcloud compute network-endpoint-groups create sneg-appkidsflixfinland --region=europe-north1 --network-endpoint-type=serverless --cloud-run-service=appkidsflixfinland
    - gcloud compute network-endpoint-groups create sneg-appkidsflixusa --region=us-central1 --network-endpoint-type=serverless --cloud-run-service=appkidsflixusa
    - gcloud compute backend-services create kidsflix-backend-global --global
    - gcloud compute backend-services add-backend kidsflix-backend-global --global --network-endpoint-group=sneg-appkidsflixfinland --network-endpoint-group-region=europe-north1
    - gcloud compute backend-services add-backend kidsflix-backend-global --global --network-endpoint-group=sneg-appkidsflixusa --network-endpoint-group-region=us-central1
    - gcloud compute url-maps create lb-kidsflix-global --default-service kidsflix-backend-global
    - gcloud compute target-http-proxies create lb-kidsflix-httpproxy --url-map=lb-kidsflix-global
    - gcloud compute addresses delete kidsflix-global-ip --global
    - gcloud compute addresses create kidsflix-global-ip --ip-version=IPV4 --global
    - gcloud compute addresses describe kidsflix-global-ip --format="get(address)" --global
    - gcloud compute forwarding-rules create kidsflix-frontend-global --address=kidsflix-global-ip --target-http-proxy=lb-kidsflix-httpproxy --global --ports=80
